version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - file-storage
#      - file-analyzer

  file-storage:
    env_file: ./file-storage/.env
    build: ./file-storage
    ports:
      - "8001:8001"
    depends_on:
      file-storage-db:
        condition: service_healthy
    volumes:
      - ./file-storage/uploads:/app/uploads
      - ./file-storage/static:/app/static
      - ./file-storage/templates:/app/templates
#
#  file-analyzer:
#    build: ./file-analyzer
#    ports:
#      - "8002:8002"

  file-storage-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: file_storage_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d file_storage_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/init_file_storage.sql:/docker-entrypoint-initdb.d/init_file_storage.sql